INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
            VALUES ('CHRIS', 'SCHAEFER', '1981-05-03');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
            VALUES ('SCOTT', 'TIGER', '1990-11-02');
INSERT INTO CONTACT (FIRST_NAME, LAST_NAME, BIRTH_DATE)
            VALUES ('JOHN', 'SMITH', '1964-02-28');
INSERT INTO contact_tel_detail (contact_id, tel_type, tel_number) VALUES (1, 'Mobile', '1234567890');
INSERT INTO contact_tel_detail (contact_id, tel_type, tel_number) VALUES (1, 'Home', '1234567890');
INSERT INTO contact_tel_detail (contact_id, tel_type, tel_number) VALUES (2, 'Home', '1234567890');

INSERT INTO HOBBY (HOBBY_ID) VALUES ('SWIMMING');
INSERT INTO HOBBY (HOBBY_ID) VALUES ('JOGGINH');
INSERT INTO HOBBY (HOBBY_ID) VALUES ('PROGRAMMING');
INSERT INTO HOBBY (HOBBY_ID) VALUES ('MOVIES');
INSERT INTO HOBBY (HOBBY_ID) VALUES ('READING');

INSERT INTO CONTACT_HOBBY_DETAIL (CONTACT_ID, HOBBY_ID) VALUES (1, 'SWIMMING');
INSERT INTO CONTACT_HOBBY_DETAIL (CONTACT_ID, HOBBY_ID) VALUES (1, 'MOVIES');
INSERT INTO CONTACT_HOBBY_DETAIL (CONTACT_ID, HOBBY_ID) VALUES (2, 'SWIMMING');